#!/bin/sh

# PXE auto installer - PART TWO
# NOTE: This is run from /etc/rc.local after D-I have rebooted
#       the machine.
#       We're going to need MySQL etc, etc be up and running to
#       be able to do the install, so this needs to be run in
#       the real FS after the D-I install.

do_install() {
    apt-get -y --no-install-recommends install $*
}

get_debconf_value () {
    debconf-get-selections | \
        egrep "^${1}[ $(printf '\t')].*${2}[ $(printf '\t')]" | \
        sed 's@.*[ \t]@@'
}

ini_unset_value () {
    local file="$1"
    local value="$2"

    sed -i "s@^\(${value}[ \t]\)=.*@#\1 = <None>@" "${file}"
}

LOCALSERVER="server.domain.tld"
LOGFILE="/var/tmp/rc.install.log"
PKGOS_VERBOSE=yes
[ -z "${DEBIAN_FRONTEND}" ] && DEBIAN_FRONTEND="noninteractive"
[ -z "${SQLDB}" ] && SQLDB="mysql" # mariadb - !!DOES NOT WORK!!
export LOCALSERVER LOGFILE DEBIAN_FRONTEND SQLDB PKGOS_VERBOSE

if [ "${1}" = "reset" ] && echo "${hostname}" | grep -iq "^blade[A-Z][0-9][0-9]"
then
    dpkg --purge mysql-server-5.6 rabbitmq-server keystone
    curl -s http://${LOCALSERVER}/PXEBoot/debconf_openstack-control.txt | \
        sed 's@\t.*@@' | sort | uniq | \
        while read pkg; do
	    echo PURGE | debconf-communicate "${pkg}"
	done
    exit 0
fi

[ -f "/var/tmp/rc.install.done" ] && exit 0

# Need to wait for the interface to come up.
while ! ping -q -c1 ftp.uk.debian.org; do sleep 5; done

exec 1<&-		# Close STDOUT file descriptor
exec 2<&-		# Close STDERR file descriptor
exec 1<>$LOGFILE	# Open STDOUT as $LOGFILE file for read and write.
exec 2>&1		# Redirect STDERR to STDOUT
chmod 0600 /var/tmp/rc.install.log

echo "=> Starting rc.install: $(date) <="

# Get the Openstack RC file. Going to need that both in the testing of
# Keystone as well as local Openstack configuration further down.
curl -s http://${LOCALSERVER}/PXEBoot/admin-openrc > /root/admin-openrc
chmod 600 /root/admin-openrc
set +x # Disable showing commands this do (password especially).
. /root/admin-openrc
if [ -z "${OS_AUTH_URL}" ]; then
    echo "Something wrong with the admin-openrc!"
    exit 1
fi

set -ex

# ======================================================================

# Make sure that we're using the real IP as hostname, not the localhost address.
sed -i "s@^127.*${hostname}@${ip}\t${hostname}.$(dnsdomainname)\t${hostname}@" /etc/hosts

apt-get update
if echo "${hostname}" | grep -iq "^blade[A-Z][0-9][0-9]"; then
    # A blade.
    echo "=> Generic blade installation."

    # Upgrade system to Sid.
    apt-get update
    apt-get -y dist-upgrade

    # Need to modify sshd config in Sid.
    # TODO: Generate new, personal, ssh keys with ECDSA.
    echo 'PubkeyAcceptedKeyTypes=+ssh-dss' >> /etc/ssh/sshd_config
    systemctl restart ssh

    # Install the HP utilities, dbconfig and Openstack packaging tools.
    do_install hp-snmp-agents hponcfg dbconfig-mysql openstack-pkg-tools \
        vlan openvswitch-switch unzip libosinfo-bin
    sed -i "s@'false'@'true'@" /etc/dbconfig-common/config

    # Remove the 4.6.0 kernel (it does not come with "aufs", which we'll need
    # for Docker). Should leave us with only 3.16.0. We remove it so that
    # it's not accidentally booted.
    dpkg --purge linux-image-4.6.0-1-amd64 linux-image-amd64

    # Disable IPv6.
    cp /etc/sysctl.conf /etc/sysctl.conf.orig
    cat <<EOF >> /etc/sysctl.conf

# Disable IPv6.
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv6.conf.eth0.disable_ipv6 = 1
net.ipv6.conf.eth1.disable_ipv6 = 1

# Disable filtering
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0

# Enable IP forwarding
net.ipv4.ip_forward = 1
EOF
    sysctl -p

    # Setup the networking and Open vSwitch.
    # TODO|NOTE: This can be "dangerous". If we don't get
    #            "br-physical" up and running, everything else
    #            here will fail!!
    #            BUT (!) it seems that MAYBE (!) it works fine IF
    #            doing from scratch.
    ipnr="$(echo "${ip}" | sed 's@.*\.@@')"
    cp /etc/network/interfaces /etc/network/interfaces.orig
    cat <<EOF > /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# =================================

# Provider/Physical network - 1 (eth1).
allow-ovs br-physical
iface br-physical inet static
	address 10.0.4.${ipnr}
	netmask 255.255.0.0
	network 10.0.4.0
	broadcast 10.0.255.255
	gateway 10.0.0.254
	dns-nameservers 10.0.0.254

auto eth1
iface eth1 inet manual
	up ifconfig \$IFACE 0.0.0.0 up
	up ip link set \$IFACE promisc on
	up ethtool -K \$IFACE gro off
	down ip link set \$IFACE promisc off
	down ifconfig \$IFACE down

# =================================

# Provider/Physical network - 2 (eth0).
allow-ovs br-infra
iface br-infra inet static
	address 10.0.3.${ipnr}
	netmask 255.255.0.0
	network 10.0.3.0
	broadcast 10.0.255.255
	gateway 10.0.0.254
	dns-nameservers 10.0.0.254

auto eth0
iface eth0 inet manual
	up ifconfig \$IFACE 0.0.0.0 up
	up ip link set \$IFACE promisc on
	up ethtool -K \$IFACE gro off
	down ip link set \$IFACE promisc off
	down ifconfig \$IFACE down
EOF

    # Setup and start the bridge interface.
    ifdown eth1 || ifconfig eth1 down
    ovs-vsctl init
    ovs-vsctl list-br | \
        while read br; do
	    ovs-vsctl del-br "${br}"
    done
    ovs-vsctl add-br br-physical
    ovs-vsctl add-br br-infra
    ovs-vsctl add-port br-physical eth1
    ovs-vsctl add-port br-infra eth0
    ifup eth1
    ifup eth0
    set +e
    /etc/init.d/openvswitch-switch stop
    /etc/init.d/openvswitch-switch start
    set -e

    # Install a "upgrade" script.
    curl -s http://${LOCALSERVER}/PXEBoot/upgrade_system.sh > \
        /usr/local/sbin/upgrade_system.sh
    chmod +x /usr/local/sbin/upgrade_system.sh
    ln -s /usr/local/sbin/upgrade_system.sh /etc/cron.daily/
fi

# Always need NTP and some basic debug tools!
do_install ntp ntpdate strace

nr="$(echo "${hostname}" | \
    sed -e 's@.*blade[A-Z]@@i' -e 's@^0@@' -e 's@[a-z]$@@')"
if echo "${hostname}" | grep -qi "^blade" && [ "${nr}" -ge "3" ]; then
    # => A Compute node!
    echo "=> Installing a Compute node."

    # Preseed debconf
    curl -s http://${LOCALSERVER}/PXEBoot/debconf_openstack-compute.txt | \
        sed "s@10\.0\.4\.3@${ip}@" | \
        debconf-set-selections

    # Install the SQL clients. Not required, but nice to have.
    if [ "${SQLDB}" = "mysql" ]; then
        do_install mysql-client-5.6
    else
        do_install mariadb-client-10.0
    fi

    # Properly seed dbconfig - It's not enough to just have it in the debconf
    # db, we also need to create the config files for dbconfig-common to use.
    for app in magnum-common nova-common; do
        admpass="$(get_debconf_value "${app}" "/mysql/admin-pass")"
        pass="$(get_debconf_value "${app}" "/mysql/app-pass")"
        user="$(get_debconf_value "${app}" "/db/app-user")"
        db="$(get_debconf_value "${app}" "/db/dbname")"

        curl -s http://${LOCALSERVER}/PXEBoot/dbconfig-common-template.conf | \
            sed -e "s@%APP%@${app}@" -e "s@%PASS%@${pass}@" \
                -e "s@%PKG%@${pkg}@" -e "s@%USER%@${user}@" \
                -e "s@%DB%@${db}@"   -e "s@%ADMPASS%@${admpass}@" \
                > "/etc/dbconfig-common/${app}.conf"
    done

    # Prepare for installing ceilometer on the Compute.
    # We need to forward traffic to localhost:27017 to 10.0.4.1:27017
    # because that's where the RabbitMQ server is running.
#    sysctl -w net.ipv4.conf.all.route_localnet=1
#    iptables -t nat -A OUTPUT -m addrtype --src-type LOCAL --dst-type LOCAL -p tcp --dport 27017 -j DNAT --to-destination 10.0.4.1
#    iptables -t nat -A POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE

    # Install the Compute packages.
    # nova-compute-ironic : Conflicts: nova-compute-kvm but 2:13.0.0-4 is to be installed
    # nova-compute-kvm : Conflicts: nova-compute-ironic but 2:13.0.0-4 is to be installed
    do_install nova-compute-kvm nova-console nova-consoleproxy \
        magnum-conductor fping ovmf designate-agent ceilometer-agent-compute \
        neutron-openvswitch-agent nova-consoleauth spice-html5
        # NOTE: !! Apparently, L3, LBaaS, VPNaaS and FWaaS agents !!
        #       !! should not run on the Compute                  !!
        #neutron-lbaas-agent neutron-l3-agent neutron-vpnaas-agent

    # Remove the portforwarding hack
#    iptables -t nat -D OUTPUT -m addrtype --src-type LOCAL --dst-type LOCAL -p tcp --dport 27017 -j DNAT --to-destination 10.0.4.1
#    iptables -t nat -D POSTROUTING -m addrtype --src-type LOCAL --dst-type UNICAST -j MASQUERADE
#    sysctl -w net.ipv4.conf.all.route_localnet=0

    # ======================================================================

    # Do local setup of Openstack.
    curl -s http://${LOCALSERVER}/PXEBoot/local_setup_openstack-compute.sh > \
        /var/tmp/local_setup_openstack-compute.sh
    sh -x /var/tmp/local_setup_openstack-compute.sh

    # Install the Nova Docker plugin.
    curl -s http://${LOCALSERVER}/PXEBoot/install_nova_docker.sh > \
        /var/tmp/install_nova_docker.sh
    sh /var/tmp/install_nova_docker.sh
elif echo "${hostname}" | grep -qi "^blade" && [ "${nr}" -le "2" ]; then
    # => A Control node
    echo "=> Installing a Control node."

    # Preseed debconf
    curl -s http://${LOCALSERVER}/PXEBoot/debconf_openstack-control.txt | \
        sed "s@10\.0\.4\.1@${ip}@" | \
        debconf-set-selections

    # Install core database packages first
    [ "${SQLDB}" = "mysql" ] && \
        server="mysql-server-5.6" || \
        server="mariadb-server-10.0"
    do_install "${server}" rabbitmq-server mongodb-server memcached

    # Create RabbitMQ user
    pass="$(get_debconf_value "barbican-common" "/rabbit_password")"
    rabbitmqctl add_user openstack "${pass}"
    rabbitmqctl set_permissions -p / openstack ".*" ".*" ".*"

    # Make SQL server bind to *
    [ "${SQLDB}" = "mysql" ] && \
        cfg="/etc/mysql/mysql.conf.d/mysqld.cnf" || \
        cfg="/etc/mysql/mariadb.conf.d/50-server.cnf"
    sed -i "s@^\(bind-address[ \t]=\).*@\1 0.0.0.0@" "${cfg}"
    sed -i "s@^#\(max_connections[ \t]=\).*@\1 5000@" "${cfg}"
    sed -i "s@^#\(server-id[ \t]=\).*@\1 ${ipnr}@" "${cfg}"
    sed -i "s@^#\(log_bin[ \t].*\)@\1@" "${cfg}"
    echo "SET GLOBAL max_connections = 5000;" | \
        mysql -uroot -p$(get_debconf_value "keystone" "mysql/admin-pass") \
              -hlocalhost mysql
    /etc/init.d/mysql restart

    # ======================================================================

    # Core-core packages installed. Let's install next step: Keystone and get
    # that working.

    # ======================================================================

    # Seed the SQL database
    user="$(grep ^user /etc/mysql/debian.cnf | tail -n1 | sed 's@.* @@')"
    pass="$(grep ^password /etc/mysql/debian.cnf | tail -n1 | sed 's@.* @@')"
    curl -s http://${LOCALSERVER}/PXEBoot/blade-users.sql-${SQLDB} | \
        mysql -hlocalhost -u"${user}" -p"${pass}" mysql

    # Properly seed dbconfig - It's not enough to just have it in the debconf
    # db, we also need to create the config files for dbconfig-common to use.
    for app in barbican cinder designate glance heat ironic magnum manila \
        mistral murano neutron nova-api nova senlin keystone trove
    do
        if [ "${app}" = "keystone" -o "${app}" = "nova-api" ]; then
            pkg="${app}"
        else
            pkg="${app}-common"
        fi

        # Most of this is primarily here because I get a postinst error when
        # installing nova-api - "You have an error in your SQL syntax".
        # If I remove the dash in the username/database (and just call it
        # "novaapi", it works).
        admpass="$(get_debconf_value "${pkg}" "/mysql/admin-pass")"
        pass="$(get_debconf_value "${pkg}" "/mysql/app-pass")"
        user="$(get_debconf_value "${pkg}" "/db/app-user")"
        db="$(get_debconf_value "${pkg}" "/db/dbname")"
        curl -s http://${LOCALSERVER}/PXEBoot/dbconfig-common-template.conf | \
            sed -e "s@%APP%@${app}@" -e "s@%PASS%@${pass}@" \
                -e "s@%PKG%@${pkg}@" -e "s@%USER%@${user}@" \
                -e "s@%DB%@${db}@"   -e "s@%ADMPASS%@${admpass}@" \
                > "/etc/dbconfig-common/${pkg}.conf"
    done

    # Prepare the configuration of the dashboard.
    mkdir -p /etc/openstack-dashboard
    curl -s http://${LOCALSERVER}/PXEBoot/dashboard.conf > \
        /etc/openstack-dashboard/local_settings.py

    # Install Openstack Authentication server and the 'openstack' script
    # as well as the dashboard.
    # TODO: Still having problem with the provided Horizon in Debian GNU/Linux.
    do_install keystone python-keystone python-openstackclient cryptsetup \
        python-django-horizon=2:9.0.0-3 openstack-dashboard=2:9.0.0-3 \
        openstack-dashboard-apache 

    # Just double check - if we can't retrieve the user list, exit here,
    # no point in continuing installing on a broken system (if Keystone
    # isn't working, nothing will).
    echo "Sleeping 30 seconds to give Keystone time to start."
    sleep 30 # Wait half a minute for keystone to come up.
    openstack user list | grep -q admin || exit 1

    # ======================================================================

    # The base packages (MySQL, RabbitMQ, Keystone etc) are all installed.
    # Let's continue with all the other services.

    # ======================================================================

    # Package variables.
    BARBICAN="barbican-api barbican-keystone-listener barbican-worker "
    CEILOMETER="ceilometer-api ceilometer-agent-ipmi ceilometer-agent-notification ceilometer-agent-central ceilometer-alarm-notifier ceilometer-collector"
    CINDER="cinder-api cinder-scheduler cinder-backup cinder-volume "
    DESIGNATE="designate-api designate-agent designate designate-central designate-mdns designate-pool-manager designate-sink designate-zone-manager"
#    FUEL="fuel-agent fuel-ha-utils fuel-migrate fuel-misc fuel-nailgun-agent fuel-notify fuel-rabbit-fence fuel-umm fuel-web-apache"
    GLANCE="glance glance-glare"
    HEAT="heat-api heat-engine "
    IRONIC="ironic-api ironic-conductor ironic-fa-deploy ironic-inspector"
    MAGNUM="magnum-api magnum-conductor"
    MANILA="manila-api manila-scheduler manila-share"
    MISTRAL="mistral-api mistral-engine mistral-executor"
    MURANO="murano-api murano-engine"
    NEUTRON="neutron-server neutron-dhcp-agent neutron-metering-agent neutron-l3-agent neutron-lbaas-agent neutron-vpnaas-agent neutron-openvswitch-agent neutron-plugin-openvswitch-agent" # neutron-fwaas-agent
    NOVA="nova-api nova-conductor nova-scheduler nova-volume"
    SENLIN="senlin-api senlin-engine "
    SWIFT="swift-account swift-container swift-object swift-plugin-s3 swift-proxy"
    if [ "${ipnr}" = "1" ]; then
        # => only on one of the storage nodes.
        SWIFT="${SWIFT} swift-object-expirer"
    fi
    TROVE="trove-api trove-guestagent trove-conductor trove-taskmanager"
    ZAQAR="zaqar-server"

    # Install Openstack services.
    # TODO: !! Isn't completely packaged yet: "${FUEL}" !! 
    do_install "${BARBICAN}" "${CEILOMETER}" "${CINDER}" "${DESIGNATE}" \
        "${FUEL}" "${GLANCE}" "${HEAT}" "${IRONIC}" "${MAGNUM}" "${MANILA}" \
        "${MISTRAL}" "${MURANO}" "${NEUTRON}" "${NOVA}" "${SENLIN}" \
        "${SWIFT}" "${TROVE}" "${ZAQAR}" haproxy nfs-kernel-server rsync \
        spice-html5

    # ======================================================================

    # Openstack is now installed. Correctly we hope - TODO: Check this somehow?
    # Time to do tune the setup for my use-case(s).

    # ======================================================================

    # Do local setup of Openstack.
    curl -s http://${LOCALSERVER}/PXEBoot/local_setup_openstack-control.sh > \
        /var/tmp/local_setup_openstack-control.sh
    sh -x /var/tmp/local_setup_openstack-control.sh
fi

# ======================================================================
# Cleanup etc.

# Remove all passwords from the debconf database.
# NOTE: This is technically pointless. It's still available
#       from the master file on LOCALSERVER.
debconf-get-selections | \
    grep "^[a-z].*[ $(printf '\t')]password[ $(printf '\t')].*" | \
    sed "s@^\([a-z].*[ $(printf '\t')]password[ $(printf '\t')]\).*@\1@" | \
    debconf-set-selections

# Remove all passwords from the dbconfig-common files.
# NOTE: This is technically pointless. It's still available
#       from the master file on LOCALSERVER.
egrep '^dbc_dbpass|^dbc_dbadmpass' /etc/dbconfig-common/* | \
    sed 's@:.*@@' | sort | uniq | \
    while read file; do
        cat "${file}" | sed -e "s@^\(dbc_dbpass='\).*@\1'@" \
            -e "s@^\(dbc_dbadmpass='\).*@\1'@" > \
            "${file}.new"
        mv "${file}.new" "${file}"
    done

apt-get -y autoremove
apt-get clean

sed -i "s@^\(sh /var/tmp/rc\.install.*\)\$@#\1@" /etc/rc.local
touch /var/tmp/rc.install.done

echo "=> W E ' R E   A L L   D O N E : $(date) <="
